### PR TITLE
Fixed several typos in comments and removed trailing spaces

### PR DESCRIPTION
**Pull request by jwillemsen**

### CODE REVIEW

**Comment by jwillemsen** [comment]
Fixed the problem that the full file was changed, now the diff shows the real changes

**Comment by jwillemsen** [comment]
Any plans to merge this?

**Comment by jwillemsen** [comment]
@GerardoPardo Thanks for accepting the pull request and the merge

**Comment by GerardoPardo** [comment]
@jwillemsen you are welcome. Apologies for the delay!

**Pull request merged**
